<Relatorio>:
    size_hint: 0.1,0.1
    name: "relatorio"
    Label:
        text: 'Relatorios'
        font_size: 0.6*self.height
        pos_hint: {'top':9,'right':5.5}
        size_hint: 1, 1


    Button:
        font_size: 0.4*self.height
        text:'Alterar'
        pos_hint: {'top':7, 'right': 6}
        on_release: app.root.current = "alterar"
        size_hint: 2, .8

    Voltar:
        on_release: app.root.current = "menu"